# Note:
# If eslint does not work in VSCode, please check:
# (1) Whether "@typescript-eslint/eslint-plugin" and "@typescript-eslint/parser"
# are npm installed locally. Should better in the same version.
# (2) Whether "VSCode ESlint extension" is installed.
# (3) If the project folder is not the root folder of your working space, please
# config the "VSCode ESlint extension" in "settings":
# ```json
# "eslint.workingDirectories": [{"mode": "auto"}]
# ```
# Note that it should be "workingDirectories" rather than "WorkingDirectories".

parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: 6
    sourceType: module
    ecmaFeatures:
        modules: true
    project: "tsconfig.json"
plugins:
    - "@typescript-eslint"
    - '@echarts-x/ec'
env:
    # Do not set `browser: true, node: true`, which introduces some global variables
    # (e.g., "require", "global"), which bypasses checks and may lead to errors.
    es6: false
globals:
    console: false
    setTimeout: true
    clearTimeout: true
    navigator: false
    process: true # Only for process.env.NODE_ENV
root: true
rules:
    # Check the rules in: node_modules/@typescript-eslint/eslint-plugin/README.md
    no-console:
        - 2
        -
            allow:
                - "warn"
                - "error"
    prefer-const: 0 # Allowed temporarily.
    no-constant-condition: 0
    comma-dangle: 0
    no-debugger: 2
    no-dupe-keys: 2
    no-empty-character-class: 2
    no-ex-assign: 2
    no-extra-boolean-cast: 0
    no-func-assign: 2
    no-inner-declarations: 2
    no-invalid-regexp: 2
    no-negated-in-lhs: 2
    no-obj-calls: 2
    no-sparse-arrays: 2
    no-unreachable: 2
    use-isnan: 2
    valid-typeof: 2
    block-scoped-var: 2
    curly:
        - 2
        - "all"
    eqeqeq:
        - 2
        - "allow-null"
    guard-for-in: 2
    no-else-return: 0
    no-labels:
        - 2
        -
            allowLoop: true
    no-eval: 2
    no-extend-native: 2
    no-extra-bind: 0
    no-implied-eval: 2
    no-iterator: 2
    no-irregular-whitespace: 2
    no-lone-blocks: 2
    no-loop-func: 2
    no-multi-str: 2
    no-native-reassign: 2
    no-new-wrappers: 2
    no-octal: 2
    no-octal-escape: 2
    no-proto: 2
    no-self-compare: 2
    no-unneeded-ternary: 2
    no-with: 2
    radix: 2
    wrap-iife:
        - 2
        - "any"
    no-delete-var: 2
    no-dupe-args: 2
    no-duplicate-case: 2
    no-label-var: 2
    no-shadow-restricted-names: 2
    no-undef: 2
    no-undef-init: 2
    "no-use-before-define": "off"
    "@typescript-eslint/no-use-before-define": 0
    brace-style:
        - 2
        - "stroustrup"
        - {}
    comma-spacing:
        - 2
        -
            before: false
            after: true
    comma-style:
        - 2
        - "last"
    new-parens: 2
    no-array-constructor: 2
    no-multi-spaces:
        - 1
        -
            ignoreEOLComments: true
            exceptions:
                Property: true
    no-new-object: 2
    no-spaced-func: 2
    no-trailing-spaces: 2
    no-extra-parens:
        - 2
        - "functions"
    no-mixed-spaces-and-tabs: 2
    one-var:
        - 2
        - "never"
    operator-linebreak:
        - 2
        - "before"
        -
            overrides:
                "=": "after"
    "quotes": "off"
    "@typescript-eslint/quotes":
        - 2
        - "single"
    "semi": "off"
    "@typescript-eslint/semi":
        - 0  # Temporarily allow.
        - "always"
    semi-spacing: 2
    keyword-spacing: 2
    key-spacing:
        - 2
        -
            beforeColon: false
            afterColon: true
    "space-before-function-paren": "off"
    "@typescript-eslint/space-before-function-paren":
        - 2
        -
            anonymous: "always"
            named: "never"
    space-before-blocks:
        - 2
        - "always"
    computed-property-spacing:
        - 2
        - "never"
    space-in-parens:
        - 2
        - "never"
    space-unary-ops: 2
    spaced-comment: 0 # Allowed temporarily.

    max-nested-callbacks:
        - 1
        - 5
    max-depth:
        - 1
        - 6
    max-len:
        - 2
        - 120
        - 4
        -
            ignoreUrls: true
            ignoreComments: true
    max-params:
        - 1
        - 15

    space-infix-ops: 2
    dot-notation:
        - 2
        -
            allowKeywords: true
            allowPattern: "^catch$"

    arrow-spacing: 2
    constructor-super: 2
    no-confusing-arrow:
        - 2
        -
            allowParens: true
    no-class-assign: 2
    no-const-assign: 2
    # no-dupe-class-members: 2
    no-this-before-super: 0
    no-var: 2
    no-duplicate-imports: 2
    prefer-rest-params: 0
    unicode-bom: 2
    max-statements-per-line: 2

    no-useless-constructor: 0

    "func-call-spacing": "off"
    "@typescript-eslint/func-call-spacing": "error"

    "no-unused-vars": "off"
    "@typescript-eslint/no-unused-vars":
        - 1
        -
            vars: "local"
            args: "none"


    "no-restricted-syntax":
        - 2
        -
            "selector": "SpreadElement"
            "message": "Spread syntax is unnecessary; it introduces verbose code after compilation."
        -
            "selector": "AssignmentPattern"
            "message": "Default parameters only apply to undefined, but zrender treats undefined and null the same."
        -
            "selector": "FunctionDeclaration[async=true]"
            "message": "No need to use async/await yet; it introduces verbose code after compilation."
        -
            "selector": "ArrowFunctionExpression[async=true]"
            "message": "No need to use async/await yet; it introduces verbose code after compilation."
        -
            "selector": "AwaitExpression"
            "message": "No need to use async/await yet; it introduces verbose code after compilation."
    "@echarts-x/ec/no-props-polyfill-uncertain":
        # Currently, zrender does not officially discard legacy platforms. The following methods are
        # not polyfilled, and alternatives are widely used in this codebase by convention, which also
        # benefits compression.
        - 2
        - {"receiver": "Array.prototype", "method": "map", "message": "Use `map` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Array.prototype", "method": "forEach", "message": "Use `each` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Array.prototype", "method": "reduce", "message": "Use `reduce` or `each` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Array.prototype", "method": "reduceRight", "message": "Use `reduce` or `each` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Array.prototype", "method": "filter", "message": "Use `filter` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Array.prototype", "method": "indexOf", "message": "Use `indexOf` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Array.prototype", "method": "find", "message": "Use `find` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Array.prototype", "method": "findIndex", "message": "Use `find` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Array.prototype", "method": "findLast", "message": "Use `find` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Array.prototype", "method": "findLastIndex", "message": "Use `find` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Array.prototype", "method": "includes", "message": "Use `indexOf` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Array.prototype", "method": "some", "message": "Use `find` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Array.prototype", "method": "flat"}
        - {"receiver": "Array.prototype", "method": "flatMap"}
        - {"receiver": "Array.prototype", "method": "at"}
        - {"receiver": "Array.prototype", "method": "every"}
        - {"receiver": "Array.prototype", "method": "fill"}
        - {"receiver": "String.prototype", "method": "startsWith", "message": "Use `String.prototype.indexOf` instead."}
        - {"receiver": "String.prototype", "method": "endsWith", "message": "Use `String.prototype.indexOf` instead."}
        - {"receiver": "String.prototype", "method": "includes", "message": "Use `String.prototype.indexOf` instead."}
        - {"receiver": "String.prototype", "method": "repeat"}
        - {"receiver": "String.prototype", "method": "padStart"}
        - {"receiver": "String.prototype", "method": "padEnd"}
        - {"receiver": "String.prototype", "method": "matchAll"}
        - {"receiver": "String.prototype", "method": "replaceAll"}
        - {"receiver": "Array", "method": "isArray", "message": "Use `isArray` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Function", "method": "bind", "message": "Use `bind` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Function.prototype", "method": "bind", "message": "Use `bind` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Date", "method": "now", "message": "Use `+(new Date())` instead."}
        - {"receiver": "Date.prototype", "method": "toJSON"}
        - {"receiver": "Object", "method": "assign", "message": "Use `extend` or `defaults` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Object", "method": "keys", "message": "Use `keys` in `zrender/src/core/util.ts` instead."}
        - {"receiver": "Object", "method": "seal", "message": "Typically not necessary in production code."}
        - {"receiver": "Object", "method": "isSealed", "message": "Typically not necessary in production code."}
        - {"receiver": "Object", "method": "freeze", "message": "Typically not necessary in production code."}
        - {"receiver": "Object", "method": "isFrozen", "message": "Typically not necessary in production code."}
        - {"receiver": "Object", "method": "isExtensible", "message": "Typically not necessary in production code."}
        - {"receiver": "Object", "method": "preventExtensions", "message": "Typically not necessary in production code."}
        - {"receiver": "Object", "method": "create", "message": "Typically not necessary in production code."}
        - {"receiver": "Object", "method": "defineProperty", "message": "Typically not necessary in production code."}
        - {"receiver": "Object", "method": "defineProperties", "message": "Typically not necessary in production code."}
        - {"receiver": "Object", "method": "getOwnPropertyDescriptor", "message": "Typically not necessary in production code."}
        - {"receiver": "Object", "method": "getOwnPropertyNames", "message": "Typically not necessary in production code."}
        - {"receiver": "Object", "method": "is", "message": "Typically not necessary in production code."}
        - {"receiver": "Object", "method": "entries", "message": "Typically not necessary in production code."}
        - {"receiver": "Object", "method": "values", "message": "Typically not necessary in production code."}
        - {"receiver": "Object", "method": "fromEntries", "message": "Typically not necessary in production code."}
        - {"receiver": "Object", "method": "hasOwn", "message": "Typically not necessary in production code."}

    # Avoid dangerous usage of globals.
    "no-restricted-globals":
        - 2
        - "event"
        - "name"
        - "length"
        - "orientation"
        - "top"
        - "parent"
        - "location"
        - "closed"
        - "jQuery"
        - "$"
        # No need to use them yet.
        - "Promise"
        # Currently, zrender does not officially discard legacy platforms. The following methods are
        # not polyfilled, and alternatives are widely used in this codebase by convention, which also
        # benefits compression.
        - {name: "Map", message: "Use `HashMap` in `zrender/src/core/util.ts` instead."}
        - {name: "Set", message: "Use `HashMap` in `zrender/src/core/util.ts` instead."}
        - {name: "WeakMap", message: "No polyfill for it. Typically it is not necessary. Use `makeInner` or `src/util/cycleCache` instead."}
        - {name: "WeakSet", message: "No polyfill for it. Typically it is not necessary. Use `makeInner` or `src/util/cycleCache` instead."}
        - {name: "Symbol", message: "No polyfill for it. Typically it is not necessary."}
        - {name: "Proxy", message: "No polyfill for it. Typically it is not necessary."}
        - {name: "Reflect", message: "No polyfill for it. Typically it is not necessary."}
        - {name: "Intl", message: "No polyfill for it. Typically it is not necessary."}
        - {name: "Atomics", message: "No polyfill for it. Typically it is not necessary."}
