name: Publish Nightly Next

on:
  schedule:
    - cron: '10 8 * * *'
  workflow_dispatch: {}
  repository_dispatch:
    types: publish-nightly-next

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'ecomfe' }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: next

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
      - name: Setup and publish nightly
        run: |
          npm run prepare:nightly-next
          npm ci
          npm run release
          npm run test
          npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
